### ISSUE TITLE
Wrong results for a record consisting of two strings separated by a boolean

### ISSUE THREAD

**Issue by zaunt** [Monospark/remix#6]
If I have the following record:

    public record Car(String manufacturer, boolean active, String model) { }

and run this:

    public static void main(String... args) {
        Car car = Records.builder(Car.class)
            .set(Car::manufacturer).to(() -> "Toyota")
            .set(Car::model).to(() -> "Corolla")
            .set(Car::active).to(() -> true)
            .build();

        System.out.println(car);
    }

I get:

    Car[manufacturer=Ford, active=true, model=null]

I.e. the model hasn't been set.

If I change the ordering of the calls to `set` like this (to match the order of the parameters in the record constructor):

        Car car = Records.builder(Car.class)
            .set(Car::manufacturer).to(() -> "Toyota")
            .set(Car::active).to(() -> true)
            .set(Car::model).to(() -> "Corolla")
            .build();

I get `org.monospark.remix.RecordBuilderException: Could not create record instance`
caused by: `java.lang.IllegalArgumentException: Incompatible types boolean and java.lang.String`.

**Comment by crschnick** [comment]
If you are interested in similar projects, I would recommend to look at [https://github.com/Randgalt/record-builder](https://github.com/Randgalt/record-builder). It uses annotation processors to achieve similar features.

**Comment by zaunt** [comment]
Don't worry. I was just looking into how you resolved a reference (like `Car::manufacturer`) to a constructor parameter. I enjoyed reading through your code. You might want to mention in the README that the project is not currently being maintained / not quite ready for production use yet.

**Comment by crschnick** [comment]
I would recommend the following approach, which is way better than mine: https://stackoverflow.com/questions/21860875/printing-debug-info-on-errors-with-java-8-lambda-expressions/21879031#21879031

**Comment by zaunt** [comment]
Oh wow, that's a lot less convoluted! Thanks for the pointer.
